### PR TITLE
Label first 5 changesets of a new user

### PR DESCRIPTION
**Pull request by bkowshik**
Continuing from here: https://github.com/mapbox/osmcha/pull/9

### CODE REVIEW

**Comment by bkowshik** [comment]
👀 into why Travis CI failed.

**Comment by bkowshik** [comment]
`1 failed, 31 passed in 42.71 seconds`

@willemarcel Does not look like the failing test is related to this change. What do you think?

**Comment by batpad** [comment]
🎉 great to have this in, thanks!

**Comment by bkowshik** [comment]
Yay! Thank you @willemarcel 😃

**Pull request merged**
